package com.sample

import com.sample.RuleSystem;

import org.kie.api.runtime.KieSession;


declare Fact
	target : String @key
	state : String @key
end

rule "Init"

    when
    then
    	insert(new Fact("Loves money", "Unknown"));

end

rule "Loves money"
	
	when
		$m: Fact(target == "Loves money", state == "Unknown")
	
	then
		RuleSystem.INSTANCE.setQuestion("Do you love money?");
        
        RuleSystem.INSTANCE.addOption("Yes", (KieSession ksess) -> { 
        	$m.setState("Yes");
        	ksess.insert(new Fact("Loves productive work", "Unknown"));
        	update($m);
        });
		RuleSystem.INSTANCE.addOption("No", (KieSession ksess) -> {
			$m.setState("No");
			update($m);
		});
		
end

rule "Loves productive work"
	
	when
		Fact(target == "Loves money", state == "Yes")
		and $p : Fact(target == "Loves productive work", state == "Unknown")
		
	then
		RuleSystem.INSTANCE.setQuestion("Do you like doing productive work?");
        
        RuleSystem.INSTANCE.addOption("Yes", (KieSession ksess) -> {
        	$p.setState("Yes");
        	update($p);
        });
		RuleSystem.INSTANCE.addOption("No", (KieSession ksess) -> {
			$p.setState("No");
        	update($p);
		});
		
end

rule "RESULT: Game critic"

	when
		Fact(target == "Loves money", state == "No")
		
	then
		RuleSystem.INSTANCE.setQuestion("RESULT: Game Critic");

end

rule "RESULT: Programmer"

	when
		Fact(target == "Loves productive work", state == "Yes")
		
	then
		RuleSystem.INSTANCE.setQuestion("RESULT: Programmer");

end

rule "RESULT: Consultant"

	when
		Fact(target == "Loves productive work", state == "No")
		
	then
		RuleSystem.INSTANCE.setQuestion("RESULT: Consultant");

end


