package com.sample

import com.sample.RuleSystem;

import org.kie.api.runtime.KieSession;

declare enum State
	UNKNOWN, TRUE, FALSE;
end

declare Money
	love : State @key
end

declare ProductiveWork
	love : State @key
end

declare Fact
	target : String
	state : String
end

rule "Init"

    when
    then
    	insert(new Money(State.UNKNOWN));

end

rule "Loves money"
	
	when
		$m: Money(love == State.UNKNOWN)
	
	then
		RuleSystem.INSTANCE.setQuestion("Do you love money?");
        
        RuleSystem.INSTANCE.addOption("Yes", (KieSession ksess) -> { 
        	$m.setLove(State.TRUE);
        	ksess.insert(new ProductiveWork(State.UNKNOWN));
        	update($m);
        });
		RuleSystem.INSTANCE.addOption("No", (KieSession ksess) -> {
			$m.setLove(State.FALSE);
			update($m);
		});
		
end

rule "Loves productive work"
	
	when
		Money(love == State.TRUE)
		and $p : ProductiveWork(love == State.UNKNOWN)
		
	then
		RuleSystem.INSTANCE.setQuestion("Do you like doing productive work?");
        
        RuleSystem.INSTANCE.addOption("Yes", (KieSession ksess) -> {
        	$p.setLove(State.TRUE);
        	update($p);
        });
		RuleSystem.INSTANCE.addOption("No", (KieSession ksess) -> {
			$p.setLove(State.FALSE);
        	update($p);
		});
		
end

rule "RESULT: Game critic"

	when
		Money(love == State.FALSE)
		
	then
		RuleSystem.INSTANCE.setQuestion("RESULT: Game Critic");

end

rule "RESULT: Programmer"

	when
		ProductiveWork(love == State.TRUE)
		
	then
		RuleSystem.INSTANCE.setQuestion("RESULT: Programmer");

end

rule "RESULT: Consultant"

	when
		ProductiveWork(love == State.FALSE)
		
	then
		RuleSystem.INSTANCE.setQuestion("RESULT: Consultant");

end


